spring:
  datasource:
#    url: jdbc:mysql://14.103.232.61:3308/cpt202?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false&nullNamePatternMatchesAll=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://116.62.42.63:3306/cpt202?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false&nullNamePatternMatchesAll=true&allowPublicKeyRetrieval=true
    username: remote_user
    password: Cpt202Group37
swagger:
  enabled: true
